require('secretjuice/kanagawa')
require('secretjuice/mappings')
require('secretjuice/telescope')
require('secretjuice/settings')
require('secretjuice/undotree')
require('secretjuice/treesitter')
require('secretjuice/fugitive')
require('secretjuice/lsp')
